#!/usr/bin/env zsh

help(){
  echo "1st _install: 
    Install brew, zsh, vim, tmux, git, fzf, gdb, nodejs(yarn), py, etc
    etc contains .docker, .yarnrc, .notable.json"  #.skhdrc, .yabairc 
}

(){
  help
}

_install(){

  xcode-select --install

  if test ! $(which brew); then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  brew update
  mas upgrade
  brew tap homebrew/bundle
  brew bundle --file=$HOME/dotfiles/Brewfile #Brewfile로 설치
  brew bundle --file=$HOME/dotfiles/Brewmas #mas로 appstore 앱 설치
  #remove old version
  brew cleanup
  brew cask cleanup
  
  # restore from Dropbox 
  # mackup restore

  # git config 
  [ ! -f $HOME/.gitconfig ] && ln -ns $HOME/dotfiles/.gitconfig $HOME/.gitconfig
  [ ! -f $HOME/.gitignore_global ] && ln -ns $HOME/dotfiles/.gitignore_global $HOME/.gitignore_global
#  [ ! -f $HOME/.gitconfig ] && ln -bns $HOME/dotfiles/.gitconfig $HOME/.gitconfig
#  [ ! -f $HOME/.gitignore_global ] && ln -bns $HOME/dotfiles/.gitignore_global $HOME/.gitignore_global
#  git config --global inlude.path ../.gitconfig

  # oh-my-zsh 
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  #nvm 
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

  nvm install --lts

  npm install --global yarn
  
  #yarn global path
  yarn config set prefix ~/.yarn 
  yarn config get prefix
  cat ~/.yarnc 

  # autoenv
  source /usr/local/opt/autoenv/activate.sh

  
}

$@
